import enum


DENOMINATOR = 256
ATTACK_NUMERATORS = (
    128, 133, 138, 143, 148, 153, 161, 171, 179, 204,
    256,
    307, 332, 358, 384, 409, 422, 435, 448, 460, 473
)
DEFENSE_NUMERATORS = (
    7, 12, 25, 38, 51, 64, 76, 102, 128, 179,
    256,
    332, 409, 486, 537, 588, 640, 691, 742, 793, 844
)
ACCURACY_NUMERATORS = (
    84, 89, 94, 102, 110, 115, 140, 153, 179, 204,
    256,
    320, 384, 409, 422, 435, 448, 460, 473, 486, 512
)
EVASION_NUMERATORS = (
    512, 486, 473, 460, 448, 435, 422, 409, 384, 345,
    256,
    204, 179, 153, 128, 102, 89, 76, 64, 51, 38
)

def get_attack_multiplier(stage: int) -> float:
    return ATTACK_NUMERATORS[stage] / DENOMINATOR

def get_defense_multiplier(stage: int) -> float:
    return DEFENSE_NUMERATORS[stage] / DENOMINATOR

def get_accuracy_multiplier(stage: int) -> float:
    return ACCURACY_NUMERATORS[stage] / DENOMINATOR

def get_evasion_multiplier(stage: int) -> float:
    return EVASION_NUMERATORS[stage] / DENOMINATOR


class TypeEffectiveness(enum.Enum):
    SUPER = 1.4
    NORMAL = 1
    NOT_VERY = 0.7
    NONE = 0


class Type(enum.Enum):
    TYPELESS = 0
    NORMAL = 1
    FIRE = 2
    WATER = 3
    GRASS = 4
    ELECTRIC = 5
    ICE = 6
    FIGHTING = 7
    POISON = 8
    GROUND = 9
    FLYING = 10
    PSYCHIC = 11
    BUG = 12
    ROCK = 13
    GHOST = 14
    DRAGON = 15
    DARK = 16
    STEEL = 17
    FAIRY = 18
    RANDOM = 19
    SPECIAL = 20

def get_type_multiplier(attack: Type, defend: Type) -> float:
    # Temporary fix
    if attack in (Type.RANDOM, Type.SPECIAL):
        attack = Type.TYPELESS
    if defend in (Type.RANDOM, Type.SPECIAL):
        defend = Type.TYPELESS
    return type_chart[attack][defend].value

type_chart = {
    Type.NORMAL: {
        Type.NORMAL: TypeEffectiveness.NORMAL,
        Type.FIRE: TypeEffectiveness.NORMAL,
        Type.WATER: TypeEffectiveness.NORMAL,
        Type.ELECTRIC: TypeEffectiveness.NORMAL,
        Type.GRASS: TypeEffectiveness.NORMAL,
        Type.ICE: TypeEffectiveness.NORMAL,
        Type.FIGHTING: TypeEffectiveness.NORMAL,
        Type.POISON: TypeEffectiveness.NORMAL,
        Type.GROUND: TypeEffectiveness.NORMAL,
        Type.FLYING: TypeEffectiveness.NORMAL,
        Type.PSYCHIC: TypeEffectiveness.NORMAL,
        Type.BUG: TypeEffectiveness.NORMAL,
        Type.ROCK: TypeEffectiveness.NOT_VERY,
        Type.GHOST: TypeEffectiveness.NONE,
        Type.DRAGON: TypeEffectiveness.NORMAL,
        Type.DARK: TypeEffectiveness.NORMAL,
        Type.STEEL: TypeEffectiveness.NOT_VERY,
        Type.FAIRY: TypeEffectiveness.NORMAL,
        Type.TYPELESS: TypeEffectiveness.NORMAL
    },
    Type.FIRE: {
        Type.NORMAL: TypeEffectiveness.NORMAL,
        Type.FIRE: TypeEffectiveness.NOT_VERY,
        Type.WATER: TypeEffectiveness.NOT_VERY,
        Type.ELECTRIC: TypeEffectiveness.NORMAL,
        Type.GRASS: TypeEffectiveness.SUPER,
        Type.ICE: TypeEffectiveness.SUPER,
        Type.FIGHTING: TypeEffectiveness.NORMAL,
        Type.POISON: TypeEffectiveness.NORMAL,
        Type.GROUND: TypeEffectiveness.NORMAL,
        Type.FLYING: TypeEffectiveness.NORMAL,
        Type.PSYCHIC: TypeEffectiveness.NORMAL,
        Type.BUG: TypeEffectiveness.SUPER,
        Type.ROCK: TypeEffectiveness.NOT_VERY,
        Type.GHOST: TypeEffectiveness.NORMAL,
        Type.DRAGON: TypeEffectiveness.NOT_VERY,
        Type.DARK: TypeEffectiveness.NORMAL,
        Type.STEEL: TypeEffectiveness.SUPER,
        Type.FAIRY: TypeEffectiveness.NORMAL,
        Type.TYPELESS: TypeEffectiveness.NORMAL
    },
    Type.WATER: {
        Type.NORMAL: TypeEffectiveness.NORMAL,
        Type.FIRE: TypeEffectiveness.SUPER,
        Type.WATER: TypeEffectiveness.NOT_VERY,
        Type.ELECTRIC: TypeEffectiveness.NORMAL,
        Type.GRASS: TypeEffectiveness.NOT_VERY,
        Type.ICE: TypeEffectiveness.NORMAL,
        Type.FIGHTING: TypeEffectiveness.NORMAL,
        Type.POISON: TypeEffectiveness.NORMAL,
        Type.GROUND: TypeEffectiveness.SUPER,
        Type.FLYING: TypeEffectiveness.NORMAL,
        Type.PSYCHIC: TypeEffectiveness.NORMAL,
        Type.BUG: TypeEffectiveness.NORMAL,
        Type.ROCK: TypeEffectiveness.SUPER,
        Type.GHOST: TypeEffectiveness.NORMAL,
        Type.DRAGON: TypeEffectiveness.NOT_VERY,
        Type.DARK: TypeEffectiveness.NORMAL,
        Type.STEEL: TypeEffectiveness.NORMAL,
        Type.FAIRY: TypeEffectiveness.NORMAL,
        Type.TYPELESS: TypeEffectiveness.NORMAL,
    },
    Type.GRASS: {
        Type.NORMAL: TypeEffectiveness.NORMAL,
        Type.FIRE: TypeEffectiveness.NOT_VERY,
        Type.WATER: TypeEffectiveness.SUPER,
        Type.ELECTRIC: TypeEffectiveness.NORMAL,
        Type.GRASS: TypeEffectiveness.NOT_VERY,
        Type.ICE: TypeEffectiveness.NORMAL,
        Type.FIGHTING: TypeEffectiveness.NORMAL,
        Type.POISON: TypeEffectiveness.NOT_VERY,
        Type.GROUND: TypeEffectiveness.SUPER,
        Type.FLYING: TypeEffectiveness.NOT_VERY,
        Type.PSYCHIC: TypeEffectiveness.NORMAL,
        Type.BUG: TypeEffectiveness.NOT_VERY,
        Type.ROCK: TypeEffectiveness.SUPER,
        Type.GHOST: TypeEffectiveness.NORMAL,
        Type.DRAGON: TypeEffectiveness.NOT_VERY,
        Type.DARK: TypeEffectiveness.NORMAL,
        Type.STEEL: TypeEffectiveness.NOT_VERY,
        Type.FAIRY: TypeEffectiveness.NORMAL,
        Type.TYPELESS: TypeEffectiveness.NORMAL,
    },
    Type.ELECTRIC: {
        Type.NORMAL: TypeEffectiveness.NORMAL,
        Type.FIRE: TypeEffectiveness.NORMAL,
        Type.WATER: TypeEffectiveness.SUPER,
        Type.ELECTRIC: TypeEffectiveness.NOT_VERY,
        Type.GRASS: TypeEffectiveness.NOT_VERY,
        Type.ICE: TypeEffectiveness.NORMAL,
        Type.FIGHTING: TypeEffectiveness.NORMAL,
        Type.POISON: TypeEffectiveness.NORMAL,
        Type.GROUND: TypeEffectiveness.NONE,
        Type.FLYING: TypeEffectiveness.SUPER,
        Type.PSYCHIC: TypeEffectiveness.NORMAL,
        Type.BUG: TypeEffectiveness.NORMAL,
        Type.ROCK: TypeEffectiveness.NORMAL,
        Type.GHOST: TypeEffectiveness.NORMAL,
        Type.DRAGON: TypeEffectiveness.NOT_VERY,
        Type.DARK: TypeEffectiveness.NORMAL,
        Type.STEEL: TypeEffectiveness.NORMAL,
        Type.FAIRY: TypeEffectiveness.NORMAL,
        Type.TYPELESS: TypeEffectiveness.NORMAL,
    },
    Type.ICE: {
        Type.NORMAL: TypeEffectiveness.NORMAL,
        Type.FIRE: TypeEffectiveness.NOT_VERY,
        Type.WATER: TypeEffectiveness.NOT_VERY,
        Type.ELECTRIC: TypeEffectiveness.NORMAL,
        Type.GRASS: TypeEffectiveness.SUPER,
        Type.ICE: TypeEffectiveness.NOT_VERY,
        Type.FIGHTING: TypeEffectiveness.NORMAL,
        Type.POISON: TypeEffectiveness.NORMAL,
        Type.GROUND: TypeEffectiveness.SUPER,
        Type.FLYING: TypeEffectiveness.SUPER,
        Type.PSYCHIC: TypeEffectiveness.NORMAL,
        Type.BUG: TypeEffectiveness.NORMAL,
        Type.ROCK: TypeEffectiveness.NORMAL,
        Type.GHOST: TypeEffectiveness.NORMAL,
        Type.DRAGON: TypeEffectiveness.SUPER,
        Type.DARK: TypeEffectiveness.NORMAL,
        Type.STEEL: TypeEffectiveness.NOT_VERY,
        Type.FAIRY: TypeEffectiveness.NORMAL,
        Type.TYPELESS: TypeEffectiveness.NORMAL,
    },
    Type.FIGHTING: {
        Type.NORMAL: TypeEffectiveness.SUPER,
        Type.FIRE: TypeEffectiveness.NORMAL,
        Type.WATER: TypeEffectiveness.NORMAL,
        Type.ELECTRIC: TypeEffectiveness.NORMAL,
        Type.GRASS: TypeEffectiveness.NORMAL,
        Type.ICE: TypeEffectiveness.SUPER,
        Type.FIGHTING: TypeEffectiveness.NORMAL,
        Type.POISON: TypeEffectiveness.NOT_VERY,
        Type.GROUND: TypeEffectiveness.NORMAL,
        Type.FLYING: TypeEffectiveness.NOT_VERY,
        Type.PSYCHIC: TypeEffectiveness.NOT_VERY,
        Type.BUG: TypeEffectiveness.NOT_VERY,
        Type.ROCK: TypeEffectiveness.SUPER,
        Type.GHOST: TypeEffectiveness.NONE,
        Type.DRAGON: TypeEffectiveness.NORMAL,
        Type.DARK: TypeEffectiveness.SUPER,
        Type.STEEL: TypeEffectiveness.SUPER,
        Type.FAIRY: TypeEffectiveness.NOT_VERY,
        Type.TYPELESS: TypeEffectiveness.NORMAL,
    },
    Type.POISON: {
        Type.NORMAL: TypeEffectiveness.NORMAL,
        Type.FIRE: TypeEffectiveness.NORMAL,
        Type.WATER: TypeEffectiveness.NORMAL,
        Type.ELECTRIC: TypeEffectiveness.NORMAL,
        Type.GRASS: TypeEffectiveness.SUPER,
        Type.ICE: TypeEffectiveness.NORMAL,
        Type.FIGHTING: TypeEffectiveness.NORMAL,
        Type.POISON: TypeEffectiveness.NOT_VERY,
        Type.GROUND: TypeEffectiveness.NOT_VERY,
        Type.FLYING: TypeEffectiveness.NORMAL,
        Type.PSYCHIC: TypeEffectiveness.NORMAL,
        Type.BUG: TypeEffectiveness.NORMAL,
        Type.ROCK: TypeEffectiveness.NOT_VERY,
        Type.GHOST: TypeEffectiveness.NOT_VERY,
        Type.DRAGON: TypeEffectiveness.NORMAL,
        Type.DARK: TypeEffectiveness.NORMAL,
        Type.STEEL: TypeEffectiveness.NONE,
        Type.FAIRY: TypeEffectiveness.SUPER,
        Type.TYPELESS: TypeEffectiveness.NORMAL,
    },
    Type.GROUND: {
        Type.NORMAL: TypeEffectiveness.NORMAL,
        Type.FIRE: TypeEffectiveness.SUPER,
        Type.WATER: TypeEffectiveness.NORMAL,
        Type.ELECTRIC: TypeEffectiveness.SUPER,
        Type.GRASS: TypeEffectiveness.NOT_VERY,
        Type.ICE: TypeEffectiveness.NORMAL,
        Type.FIGHTING: TypeEffectiveness.NORMAL,
        Type.POISON: TypeEffectiveness.SUPER,
        Type.GROUND: TypeEffectiveness.NORMAL,
        Type.FLYING: TypeEffectiveness.NONE,
        Type.PSYCHIC: TypeEffectiveness.NORMAL,
        Type.BUG: TypeEffectiveness.NOT_VERY,
        Type.ROCK: TypeEffectiveness.SUPER,
        Type.GHOST: TypeEffectiveness.NORMAL,
        Type.DRAGON: TypeEffectiveness.NORMAL,
        Type.DARK: TypeEffectiveness.NORMAL,
        Type.STEEL: TypeEffectiveness.SUPER,
        Type.FAIRY: TypeEffectiveness.NORMAL,
        Type.TYPELESS: TypeEffectiveness.NORMAL,
    },
    Type.FLYING: {
        Type.NORMAL: TypeEffectiveness.NORMAL,
        Type.FIRE: TypeEffectiveness.NORMAL,
        Type.WATER: TypeEffectiveness.NORMAL,
        Type.ELECTRIC: TypeEffectiveness.NOT_VERY,
        Type.GRASS: TypeEffectiveness.SUPER,
        Type.ICE: TypeEffectiveness.NORMAL,
        Type.FIGHTING: TypeEffectiveness.SUPER,
        Type.POISON: TypeEffectiveness.NORMAL,
        Type.GROUND: TypeEffectiveness.NORMAL,
        Type.FLYING: TypeEffectiveness.NORMAL,
        Type.PSYCHIC: TypeEffectiveness.NORMAL,
        Type.BUG: TypeEffectiveness.SUPER,
        Type.ROCK: TypeEffectiveness.NOT_VERY,
        Type.GHOST: TypeEffectiveness.NORMAL,
        Type.DRAGON: TypeEffectiveness.NORMAL,
        Type.DARK: TypeEffectiveness.NORMAL,
        Type.STEEL: TypeEffectiveness.NOT_VERY,
        Type.FAIRY: TypeEffectiveness.NORMAL,
        Type.TYPELESS: TypeEffectiveness.NORMAL,
    },
    Type.PSYCHIC: {
        Type.NORMAL: TypeEffectiveness.NORMAL,
        Type.FIRE: TypeEffectiveness.NORMAL,
        Type.WATER: TypeEffectiveness.NORMAL,
        Type.ELECTRIC: TypeEffectiveness.NORMAL,
        Type.GRASS: TypeEffectiveness.NORMAL,
        Type.ICE: TypeEffectiveness.NORMAL,
        Type.FIGHTING: TypeEffectiveness.SUPER,
        Type.POISON: TypeEffectiveness.SUPER,
        Type.GROUND: TypeEffectiveness.NORMAL,
        Type.FLYING: TypeEffectiveness.NORMAL,
        Type.PSYCHIC: TypeEffectiveness.NOT_VERY,
        Type.BUG: TypeEffectiveness.NORMAL,
        Type.ROCK: TypeEffectiveness.NORMAL,
        Type.GHOST: TypeEffectiveness.NORMAL,
        Type.DRAGON: TypeEffectiveness.NORMAL,
        Type.DARK: TypeEffectiveness.NONE,
        Type.STEEL: TypeEffectiveness.NOT_VERY,
        Type.FAIRY: TypeEffectiveness.NORMAL,
        Type.TYPELESS: TypeEffectiveness.NORMAL,
    },
    Type.BUG: {
        Type.NORMAL: TypeEffectiveness.NORMAL,
        Type.FIRE: TypeEffectiveness.NOT_VERY,
        Type.WATER: TypeEffectiveness.NORMAL,
        Type.ELECTRIC: TypeEffectiveness.NORMAL,
        Type.GRASS: TypeEffectiveness.SUPER,
        Type.ICE: TypeEffectiveness.NORMAL,
        Type.FIGHTING: TypeEffectiveness.NOT_VERY,
        Type.POISON: TypeEffectiveness.NOT_VERY,
        Type.GROUND: TypeEffectiveness.NORMAL,
        Type.FLYING: TypeEffectiveness.NOT_VERY,
        Type.PSYCHIC: TypeEffectiveness.SUPER,
        Type.BUG: TypeEffectiveness.NORMAL,
        Type.ROCK: TypeEffectiveness.NORMAL,
        Type.GHOST: TypeEffectiveness.NOT_VERY,
        Type.DRAGON: TypeEffectiveness.NORMAL,
        Type.DARK: TypeEffectiveness.SUPER,
        Type.STEEL: TypeEffectiveness.NOT_VERY,
        Type.FAIRY: TypeEffectiveness.NOT_VERY,
        Type.TYPELESS: TypeEffectiveness.NORMAL,
    },
    Type.ROCK: {
        Type.NORMAL: TypeEffectiveness.NORMAL,
        Type.FIRE: TypeEffectiveness.SUPER,
        Type.WATER: TypeEffectiveness.NORMAL,
        Type.ELECTRIC: TypeEffectiveness.NORMAL,
        Type.GRASS: TypeEffectiveness.NORMAL,
        Type.ICE: TypeEffectiveness.SUPER,
        Type.FIGHTING: TypeEffectiveness.NOT_VERY,
        Type.POISON: TypeEffectiveness.NORMAL,
        Type.GROUND: TypeEffectiveness.NOT_VERY,
        Type.FLYING: TypeEffectiveness.SUPER,
        Type.PSYCHIC: TypeEffectiveness.NORMAL,
        Type.BUG: TypeEffectiveness.SUPER,
        Type.ROCK: TypeEffectiveness.NORMAL,
        Type.GHOST: TypeEffectiveness.NORMAL,
        Type.DRAGON: TypeEffectiveness.NORMAL,
        Type.DARK: TypeEffectiveness.NORMAL,
        Type.STEEL: TypeEffectiveness.NOT_VERY,
        Type.FAIRY: TypeEffectiveness.NORMAL,
        Type.TYPELESS: TypeEffectiveness.NORMAL,
    },
    Type.GHOST: {
        Type.NORMAL: TypeEffectiveness.NONE,
        Type.FIRE: TypeEffectiveness.NORMAL,
        Type.WATER: TypeEffectiveness.NORMAL,
        Type.ELECTRIC: TypeEffectiveness.NORMAL,
        Type.GRASS: TypeEffectiveness.NORMAL,
        Type.ICE: TypeEffectiveness.NORMAL,
        Type.FIGHTING: TypeEffectiveness.NORMAL,
        Type.POISON: TypeEffectiveness.NORMAL,
        Type.GROUND: TypeEffectiveness.NORMAL,
        Type.FLYING: TypeEffectiveness.NORMAL,
        Type.PSYCHIC: TypeEffectiveness.SUPER,
        Type.BUG: TypeEffectiveness.NORMAL,
        Type.ROCK: TypeEffectiveness.NORMAL,
        Type.GHOST: TypeEffectiveness.SUPER,
        Type.DRAGON: TypeEffectiveness.NORMAL,
        Type.DARK: TypeEffectiveness.NOT_VERY,
        Type.STEEL: TypeEffectiveness.NORMAL,
        Type.FAIRY: TypeEffectiveness.NORMAL,
        Type.TYPELESS: TypeEffectiveness.NORMAL,
    },
    Type.DRAGON: {
        Type.NORMAL: TypeEffectiveness.NORMAL,
        Type.FIRE: TypeEffectiveness.NORMAL,
        Type.WATER: TypeEffectiveness.NORMAL,
        Type.ELECTRIC: TypeEffectiveness.NORMAL,
        Type.GRASS: TypeEffectiveness.NORMAL,
        Type.ICE: TypeEffectiveness.NORMAL,
        Type.FIGHTING: TypeEffectiveness.NORMAL,
        Type.POISON: TypeEffectiveness.NORMAL,
        Type.GROUND: TypeEffectiveness.NORMAL,
        Type.FLYING: TypeEffectiveness.NORMAL,
        Type.PSYCHIC: TypeEffectiveness.NORMAL,
        Type.BUG: TypeEffectiveness.NORMAL,
        Type.ROCK: TypeEffectiveness.NORMAL,
        Type.GHOST: TypeEffectiveness.NORMAL,
        Type.DRAGON: TypeEffectiveness.SUPER,
        Type.DARK: TypeEffectiveness.NORMAL,
        Type.STEEL: TypeEffectiveness.NOT_VERY,
        Type.FAIRY: TypeEffectiveness.NONE,
        Type.TYPELESS: TypeEffectiveness.NORMAL,
    },
    Type.DARK: {
        Type.NORMAL: TypeEffectiveness.NORMAL,
        Type.FIRE: TypeEffectiveness.NORMAL,
        Type.WATER: TypeEffectiveness.NORMAL,
        Type.ELECTRIC: TypeEffectiveness.NORMAL,
        Type.GRASS: TypeEffectiveness.NORMAL,
        Type.ICE: TypeEffectiveness.NORMAL,
        Type.FIGHTING: TypeEffectiveness.NOT_VERY,
        Type.POISON: TypeEffectiveness.NORMAL,
        Type.GROUND: TypeEffectiveness.NORMAL,
        Type.FLYING: TypeEffectiveness.NORMAL,
        Type.PSYCHIC: TypeEffectiveness.SUPER,
        Type.BUG: TypeEffectiveness.NORMAL,
        Type.ROCK: TypeEffectiveness.NORMAL,
        Type.GHOST: TypeEffectiveness.SUPER,
        Type.DRAGON: TypeEffectiveness.NORMAL,
        Type.DARK: TypeEffectiveness.NOT_VERY,
        Type.STEEL: TypeEffectiveness.NORMAL,
        Type.FAIRY: TypeEffectiveness.NOT_VERY,
        Type.TYPELESS: TypeEffectiveness.NORMAL,
    },
    Type.STEEL: {
        Type.NORMAL: TypeEffectiveness.NORMAL,
        Type.FIRE: TypeEffectiveness.NOT_VERY,
        Type.WATER: TypeEffectiveness.NOT_VERY,
        Type.ELECTRIC: TypeEffectiveness.NOT_VERY,
        Type.GRASS: TypeEffectiveness.NORMAL,
        Type.ICE: TypeEffectiveness.SUPER,
        Type.FIGHTING: TypeEffectiveness.NORMAL,
        Type.POISON: TypeEffectiveness.NORMAL,
        Type.GROUND: TypeEffectiveness.NORMAL,
        Type.FLYING: TypeEffectiveness.NORMAL,
        Type.PSYCHIC: TypeEffectiveness.NORMAL,
        Type.BUG: TypeEffectiveness.NORMAL,
        Type.ROCK: TypeEffectiveness.SUPER,
        Type.GHOST: TypeEffectiveness.NORMAL,
        Type.DRAGON: TypeEffectiveness.NORMAL,
        Type.DARK: TypeEffectiveness.NORMAL,
        Type.STEEL: TypeEffectiveness.NOT_VERY,
        Type.FAIRY: TypeEffectiveness.SUPER,
        Type.TYPELESS: TypeEffectiveness.NORMAL,
    },
    Type.FAIRY: {
        Type.NORMAL: TypeEffectiveness.NORMAL,
        Type.FIRE: TypeEffectiveness.NOT_VERY,
        Type.WATER: TypeEffectiveness.NORMAL,
        Type.ELECTRIC: TypeEffectiveness.NORMAL,
        Type.GRASS: TypeEffectiveness.NORMAL,
        Type.ICE: TypeEffectiveness.NORMAL,
        Type.FIGHTING: TypeEffectiveness.SUPER,
        Type.POISON: TypeEffectiveness.NOT_VERY,
        Type.GROUND: TypeEffectiveness.NORMAL,
        Type.FLYING: TypeEffectiveness.NORMAL,
        Type.PSYCHIC: TypeEffectiveness.NORMAL,
        Type.BUG: TypeEffectiveness.NORMAL,
        Type.ROCK: TypeEffectiveness.NORMAL,
        Type.GHOST: TypeEffectiveness.NORMAL,
        Type.DRAGON: TypeEffectiveness.SUPER,
        Type.DARK: TypeEffectiveness.SUPER,
        Type.STEEL: TypeEffectiveness.NOT_VERY,
        Type.FAIRY: TypeEffectiveness.NORMAL,
        Type.TYPELESS: TypeEffectiveness.NORMAL,
    },
    Type.TYPELESS: {
        Type.NORMAL: TypeEffectiveness.NORMAL,
        Type.FIRE: TypeEffectiveness.NORMAL,
        Type.WATER: TypeEffectiveness.NORMAL,
        Type.ELECTRIC: TypeEffectiveness.NORMAL,
        Type.GRASS: TypeEffectiveness.NORMAL,
        Type.ICE: TypeEffectiveness.NORMAL,
        Type.FIGHTING: TypeEffectiveness.NORMAL,
        Type.POISON: TypeEffectiveness.NORMAL,
        Type.GROUND: TypeEffectiveness.NORMAL,
        Type.FLYING: TypeEffectiveness.NORMAL,
        Type.PSYCHIC: TypeEffectiveness.NORMAL,
        Type.BUG: TypeEffectiveness.NORMAL,
        Type.ROCK: TypeEffectiveness.NORMAL,
        Type.GHOST: TypeEffectiveness.NORMAL,
        Type.DRAGON: TypeEffectiveness.NORMAL,
        Type.DARK: TypeEffectiveness.NORMAL,
        Type.STEEL: TypeEffectiveness.NORMAL,
        Type.FAIRY: TypeEffectiveness.NORMAL,
        Type.TYPELESS: TypeEffectiveness.NORMAL,
    }
}
